# Generated by Django 4.1.2 on 2022-10-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_groupprofile_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='customuser',
            name='owner',
            field=models.BooleanField(default=False),
        ),
    ]
